// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftp.actions;

import java.io.File;
import java.io.FileInputStream;
import java.nio.charset.Charset;
import org.apache.commons.io.IOUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import net.schmizz.sshj.sftp.StatefulSFTPClient;
import sftp.impl.SFTP;

/**
 * Retrieve a file from the SFTP server and store its contents within a string.
 * This action was introduced for optimization purposes.
 * In case the remote file is assumed to be a text file and should be directly processed, it doesn't make sense to store it as a FileDocument (leading to upload/download to e.g. S3 buckets).
 */
public class GetAsString extends CustomJavaAction<java.lang.String>
{
	private java.lang.String remoteFile;

	public GetAsString(IContext context, java.lang.String remoteFile)
	{
		super(context);
		this.remoteFile = remoteFile;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StatefulSFTPClient client = SFTP.getClient(getContext());
		File tmpFile = File.createTempFile("tmp", ".txt");
		client.get(remoteFile, tmpFile.getAbsolutePath());
		String result = IOUtils.toString(new FileInputStream(tmpFile), Charset.forName("UTF-8"));
		tmpFile.delete();
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetAsString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
