// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftp.actions;

import java.security.PublicKey;
import org.apache.commons.codec.binary.Base64;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import net.schmizz.sshj.SSHClient;
import net.schmizz.sshj.common.SecurityUtils;
import net.schmizz.sshj.transport.verification.HostKeyVerifier;
import sftp.proxies.HostKey;

/**
 * Retrieves the HostKey from the session.
 */
public class GetHostKey extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __configuration;
	private sftp.proxies.Configuration configuration;

	public GetHostKey(IContext context, IMendixObject configuration)
	{
		super(context);
		this.__configuration = configuration;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.configuration = __configuration == null ? null : sftp.proxies.Configuration.initialize(getContext(), __configuration);

		// BEGIN USER CODE
		SSHClient client = new SSHClient();
		PubKeyHostVerifier verifier = new PubKeyHostVerifier();
		client.addHostKeyVerifier(verifier);
		client.setConnectTimeout(configuration.getConnectTimeout());
		client.connect(configuration.getHostname(), configuration.getPort());
		client.close();
		
		HostKey hostKey = new HostKey(getContext());
		hostKey.setAlgorithm(verifier.pubKey.getAlgorithm());
		hostKey.setFormat(verifier.pubKey.getFormat());
		hostKey.setFingerprint(SecurityUtils.getFingerprint(verifier.pubKey));
		hostKey.setKey(Base64.encodeBase64String(verifier.pubKey.getEncoded()));
		
		return hostKey.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetHostKey";
	}

	// BEGIN EXTRA CODE
	class PubKeyHostVerifier implements HostKeyVerifier {
		PublicKey pubKey = null;
		
		@Override
		public boolean verify(String hostname, int port, PublicKey key) {
			pubKey = key;
			return true;
		}
		
	}
	// END EXTRA CODE
}
