// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftp.actions;

import java.util.Date;
import java.util.LinkedList;
import java.util.Vector;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import net.schmizz.sshj.sftp.FileAttributes;
import net.schmizz.sshj.sftp.FileMode;
import net.schmizz.sshj.sftp.RemoteResourceInfo;
import net.schmizz.sshj.sftp.StatefulSFTPClient;
import sftp.impl.SFTP;
import sftp.proxies.FileType;
import sftp.proxies.RemoteFile;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Retrieves a list of files and directories from the remote SFTP server as RemoteFile objects.
 */
public class List extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String path;

	public List(IContext context, java.lang.String path)
	{
		super(context);
		this.path = path;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		StatefulSFTPClient client = SFTP.getClient(getContext());
		java.util.List<IMendixObject> result = new LinkedList<>();
		
		java.util.List<RemoteResourceInfo> list = client.ls(path);
		
		for (RemoteResourceInfo entry : list) {
			FileAttributes attrs = entry.getAttributes();
			RemoteFile rf = new RemoteFile(getContext());
			rf.setPath(path);
			rf.setName(entry.getName());
			rf.setLastModificationDate(new Date(attrs.getMtime() * 1000L));
			rf.setSize(attrs.getSize());
			
			if (attrs.getType() == FileMode.Type.DIRECTORY) {
				rf.setFileType(FileType.Directory);
			} else if (attrs.getType() == FileMode.Type.REGULAR) {
				rf.setFileType(FileType.File);
			}
			result.add(rf.getMendixObject());
		}
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "List";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
