// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftp.actions;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import com.jcraft.jsch.ChannelSftp;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import sftp.impl.SFTP;

/**
 * Creates and uploads a file on a SFTP server coming from a String.
 * This action was introduced for optimization purposes.
 * In case the remote file is assumed to be a text file and should be directly processed, it doesn't make sense to store it as a FileDocument (leading to upload/download to e.g. S3 buckets).
 */
public class PutAsString extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String destination;
	private java.lang.String contents;

	public PutAsString(IContext context, java.lang.String destination, java.lang.String contents)
	{
		super(context);
		this.destination = destination;
		this.contents = contents;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ChannelSftp channel = SFTP.getChannel(getContext());
		channel.put(new ByteArrayInputStream(contents.getBytes(StandardCharsets.UTF_8)), destination);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "PutAsString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
