// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sftp.proxies;

public class PutAsStringRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject putAsStringRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SFTP.PutAsStringRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Filename("Filename"),
		Contents("Contents"),
		PutAsStringRequest_Explore("SFTP.PutAsStringRequest_Explore");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PutAsStringRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SFTP.PutAsStringRequest"));
	}

	protected PutAsStringRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject putAsStringRequestMendixObject)
	{
		if (putAsStringRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SFTP.PutAsStringRequest", putAsStringRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SFTP.PutAsStringRequest");

		this.putAsStringRequestMendixObject = putAsStringRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PutAsStringRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sftp.proxies.PutAsStringRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sftp.proxies.PutAsStringRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sftp.proxies.PutAsStringRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sftp.proxies.PutAsStringRequest(context, mendixObject);
	}

	public static sftp.proxies.PutAsStringRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sftp.proxies.PutAsStringRequest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Filename
	 */
	public final java.lang.String getFilename()
	{
		return getFilename(getContext());
	}

	/**
	 * @param context
	 * @return value of Filename
	 */
	public final java.lang.String getFilename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Filename.toString());
	}

	/**
	 * Set value of Filename
	 * @param filename
	 */
	public final void setFilename(java.lang.String filename)
	{
		setFilename(getContext(), filename);
	}

	/**
	 * Set value of Filename
	 * @param context
	 * @param filename
	 */
	public final void setFilename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filename)
	{
		getMendixObject().setValue(context, MemberNames.Filename.toString(), filename);
	}

	/**
	 * @return value of Contents
	 */
	public final java.lang.String getContents()
	{
		return getContents(getContext());
	}

	/**
	 * @param context
	 * @return value of Contents
	 */
	public final java.lang.String getContents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Contents.toString());
	}

	/**
	 * Set value of Contents
	 * @param contents
	 */
	public final void setContents(java.lang.String contents)
	{
		setContents(getContext(), contents);
	}

	/**
	 * Set value of Contents
	 * @param context
	 * @param contents
	 */
	public final void setContents(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contents)
	{
		getMendixObject().setValue(context, MemberNames.Contents.toString(), contents);
	}

	/**
	 * @return value of PutAsStringRequest_Explore
	 */
	public final sftp.proxies.Explore getPutAsStringRequest_Explore() throws com.mendix.core.CoreException
	{
		return getPutAsStringRequest_Explore(getContext());
	}

	/**
	 * @param context
	 * @return value of PutAsStringRequest_Explore
	 */
	public final sftp.proxies.Explore getPutAsStringRequest_Explore(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sftp.proxies.Explore result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PutAsStringRequest_Explore.toString());
		if (identifier != null)
			result = sftp.proxies.Explore.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PutAsStringRequest_Explore
	 * @param putasstringrequest_explore
	 */
	public final void setPutAsStringRequest_Explore(sftp.proxies.Explore putasstringrequest_explore)
	{
		setPutAsStringRequest_Explore(getContext(), putasstringrequest_explore);
	}

	/**
	 * Set value of PutAsStringRequest_Explore
	 * @param context
	 * @param putasstringrequest_explore
	 */
	public final void setPutAsStringRequest_Explore(com.mendix.systemwideinterfaces.core.IContext context, sftp.proxies.Explore putasstringrequest_explore)
	{
		if (putasstringrequest_explore == null)
			getMendixObject().setValue(context, MemberNames.PutAsStringRequest_Explore.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PutAsStringRequest_Explore.toString(), putasstringrequest_explore.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return putAsStringRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sftp.proxies.PutAsStringRequest that = (sftp.proxies.PutAsStringRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SFTP.PutAsStringRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
