// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package encryption.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Encryption module
	public static java.lang.String decrypt(IContext context, java.lang.String _encrypted)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Encrypted", _encrypted);
			return (java.lang.String)Core.execute(context, "Encryption.Decrypt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void decrypt_Document(IContext context, system.proxies.FileDocument _fileDocument_Output, system.proxies.FileDocument _fileDocument_ToDecrypt, encryption.proxies.PGPCertificate _privateKeyForDecryption)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("FileDocument_Output", _fileDocument_Output == null ? null : _fileDocument_Output.getMendixObject());
			params.put("FileDocument_ToDecrypt", _fileDocument_ToDecrypt == null ? null : _fileDocument_ToDecrypt.getMendixObject());
			params.put("PrivateKeyForDecryption", _privateKeyForDecryption == null ? null : _privateKeyForDecryption.getMendixObject());
			Core.execute(context, "Encryption.Decrypt_Document", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static encryption.proxies.PGPCertificate dS_GetAssociatedPubKey(IContext context, encryption.proxies.PGPCertificate _certificate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Certificate", _certificate == null ? null : _certificate.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "Encryption.DS_GetAssociatedPubKey", params);
			return result == null ? null : encryption.proxies.PGPCertificate.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String encrypt(IContext context, java.lang.String _plain)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Plain", _plain);
			return (java.lang.String)Core.execute(context, "Encryption.Encrypt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void encrypt_Document(IContext context, system.proxies.FileDocument _fileDocument_ToEncrypt, system.proxies.FileDocument _fileDocument_Output, encryption.proxies.PGPCertificate _externalPubKey, encryption.proxies.PGPCertificate _signingPrivateKey_Optional)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("FileDocument_ToEncrypt", _fileDocument_ToEncrypt == null ? null : _fileDocument_ToEncrypt.getMendixObject());
			params.put("FileDocument_Output", _fileDocument_Output == null ? null : _fileDocument_Output.getMendixObject());
			params.put("ExternalPubKey", _externalPubKey == null ? null : _externalPubKey.getMendixObject());
			params.put("SigningPrivateKey_Optional", _signingPrivateKey_Optional == null ? null : _signingPrivateKey_Optional.getMendixObject());
			Core.execute(context, "Encryption.Encrypt_Document", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_ChangePasswordSave(IContext context, encryption.proxies.PasswordData _passwordData)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PasswordData", _passwordData == null ? null : _passwordData.getMendixObject());
			Core.execute(context, "Encryption.MB_ChangePasswordSave", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_GenerateCertificate(IContext context, encryption.proxies.PGPCertificate _certificate_PrivateKey)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Certificate_PrivateKey", _certificate_PrivateKey == null ? null : _certificate_PrivateKey.getMendixObject());
			Core.execute(context, "Encryption.MB_GenerateCertificate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_GenerateKeyShowPage(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Encryption.MB_GenerateKeyShowPage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_NewPrivateKey(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Encryption.MB_NewPrivateKey", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_NewPubKey(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "Encryption.MB_NewPubKey", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_OpenCertificateDetails(IContext context, encryption.proxies.PGPCertificate _certificate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Certificate", _certificate == null ? null : _certificate.getMendixObject());
			Core.execute(context, "Encryption.MB_OpenCertificateDetails", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_SaveCertificate(IContext context, encryption.proxies.PGPCertificate _certificate)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Certificate", _certificate == null ? null : _certificate.getMendixObject());
			Core.execute(context, "Encryption.MB_SaveCertificate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_ShowChangePassword(IContext context, encryption.proxies.ExampleConfiguration _exampleConfiguration)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ExampleConfiguration", _exampleConfiguration == null ? null : _exampleConfiguration.getMendixObject());
			Core.execute(context, "Encryption.MB_ShowChangePassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}